### Register user
POST http://localhost:5001/users/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@gmail.com"
}


### Create project
POST http://localhost:5001/projects/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMTE4Nzc5YS05Nzk4LTRkZTQtYmI5Yi1iZjIyZDc0YzI4YTciLCJpYXQiOjE3MzUzODYzMTIsImV4cCI6MTczNTQ3MjcxMn0.C-65W8I3YmlzRKNWYZzrnKUvbSrR4mSxF4pfzKnKL7E

{
  "title": "My First Project",
  "description": "This is a description of my projects."
}

### Create task
POST http://localhost:5001/tasks/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMTE4Nzc5YS05Nzk4LTRkZTQtYmI5Yi1iZjIyZDc0YzI4YTciLCJpYXQiOjE3MzUzODYzMTIsImV4cCI6MTczNTQ3MjcxMn0.C-65W8I3YmlzRKNWYZzrnKUvbSrR4mSxF4pfzKnKL7E

{
  "title": "Create API",
  "description": "Implement API endpoint for tasks",
  "deadline": "2024-01-15T00:00:00.000Z",
  "projectId": "4d517a26-d9d9-4616-bc0d-285009326686"
}

### Assign task to assignee
PUT http://localhost:5001/tasks/assign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMTE4Nzc5YS05Nzk4LTRkZTQtYmI5Yi1iZjIyZDc0YzI4YTciLCJpYXQiOjE3MzUzODYzMTIsImV4cCI6MTczNTQ3MjcxMn0.C-65W8I3YmlzRKNWYZzrnKUvbSrR4mSxF4pfzKnKL7E

{
  "taskId": "e373bbea-6522-40c0-9688-8eec962ae50c"
}

### Update status
PUT http://localhost:5001/tasks/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMTE4Nzc5YS05Nzk4LTRkZTQtYmI5Yi1iZjIyZDc0YzI4YTciLCJpYXQiOjE3MzUzODYzMTIsImV4cCI6MTczNTQ3MjcxMn0.C-65W8I3YmlzRKNWYZzrnKUvbSrR4mSxF4pfzKnKL7E

{
  "taskId": "e373bbea-6522-40c0-9688-8eec962ae50c",
  "status": "completed"
}

### Fetch projects with tasks
GET http://localhost:5001/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMTE4Nzc5YS05Nzk4LTRkZTQtYmI5Yi1iZjIyZDc0YzI4YTciLCJpYXQiOjE3MzUzODYzMTIsImV4cCI6MTczNTQ3MjcxMn0.C-65W8I3YmlzRKNWYZzrnKUvbSrR4mSxF4pfzKnKL7E

### Fetch developer work time
GET http://localhost:5001/tasks/work-time
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMTE4Nzc5YS05Nzk4LTRkZTQtYmI5Yi1iZjIyZDc0YzI4YTciLCJpYXQiOjE3MzUzODYzMTIsImV4cCI6MTczNTQ3MjcxMn0.C-65W8I3YmlzRKNWYZzrnKUvbSrR4mSxF4pfzKnKL7E

### Fetch developer's work time with filters by project
GET http://localhost:5001/tasks/work-time/filtered?projectId=4d517a26-d9d9-4616-bc0d-285009326686
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMTE4Nzc5YS05Nzk4LTRkZTQtYmI5Yi1iZjIyZDc0YzI4YTciLCJpYXQiOjE3MzUzODYzMTIsImV4cCI6MTczNTQ3MjcxMn0.C-65W8I3YmlzRKNWYZzrnKUvbSrR4mSxF4pfzKnKL7E

### Fetch developer's work time with filters by time
GET http://localhost:5001/tasks/work-time/filtered?projectId=4d517a26-d9d9-4616-bc0d-285009326686&startDate=2024-12-01&endDate=2024-12-31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMTE4Nzc5YS05Nzk4LTRkZTQtYmI5Yi1iZjIyZDc0YzI4YTciLCJpYXQiOjE3MzUzODYzMTIsImV4cCI6MTczNTQ3MjcxMn0.C-65W8I3YmlzRKNWYZzrnKUvbSrR4mSxF4pfzKnKL7E
